=== yyitsz/myjavastudio/RecourceConverter/RecourceConverter/SourceConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--Created with Liquid XML Studio - FREE Community Edition (http://www.liquid-technologies.com)-->
<xs:schema xmlns:mstns="http://tempuri.org/SourceConfig.xsd" elementFormDefault="qualified" targetNamespace="http://tempuri.org/SourceConfig.xsd" id="SourceConfig" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="LanguageSetting">
    <xs:attribute name="Language" type="xs:string" use="required" />
    <xs:attribute name="LanguageCode" type="xs:string" use="required" />
    <xs:attribute name="Column" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="Setting">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="LanguagetSetting" type="mstns:LanguageSetting" />
    </xs:sequence>
    <xs:attribute name="Type" type="xs:string" use="required" />
    <xs:attribute name="SourceFilePath" type="xs:string" use="required" />
    <xs:attribute name="IdColumn" type="xs:string" use="required" />
    <xs:attribute name="DeletedColumn" type="xs:string" use="required" />
    <xs:attribute name="TypeColumn" type="xs:string" />
    <xs:attribute name="SheetName" type="xs:string" />
    <xs:attribute name="RowStartIndex" type="xs:int" use="required" />
    <xs:attribute name="TotalColumns" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ApplicationSetting">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="Setting" type="mstns:Setting" />
    </xs:sequence>
    <xs:attribute name="ApplicationName" type="xs:string" use="required" />
    <xs:attribute name="ResourcePath" type="xs:string" use="required" />
    <xs:attribute name="ResourceName" type="xs:string" use="required" />
    <xs:attribute name="IsDefault" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:element name="AppConfigs">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="AppSetting" type="mstns:ApplicationSetting" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yyitsz/myjavastudio/RecourceConverter/RecourceConverter/SourceConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<AppConfigs xmlns="http://tempuri.org/SourceConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tempuri.org/SourceConfig.xsd SourceConfig.xsd">
  <!--<AppSetting ApplicationName="MSS-D" ResourcePath="DD:\MyWorkspace\MSS-D\mss-client-1.0\Taifook.MSS.Resources\Properties\" ResourceName="Resources.resx">
    <Setting Type="Message" SourceFilePath="\\10.100.1.124\test\20080428HKFS\Field\MSS_Message_0.4.xls" IdColumn="R" DeletedColumn="H" TypeColumn="M" SheetName="Message$" RowStartIndex="5">
      <LanguagetSetting Language="en" LanguageCode="" Column="V" />
      <LanguagetSetting Language="zh-cn" LanguageCode="zh-cn" Column="X">
      </LanguagetSetting>
      <LanguagetSetting Language="zh-tw" LanguageCode="zh-tw" Column="W">
      </LanguagetSetting>
    </Setting>
    <Setting Type="Field" SourceFilePath="\\10.100.1.124\test\20080428HKFS\Field\MSS_FieldLabel_0.5.xls" IdColumn="P" DeletedColumn="D" TypeColumn="M" SheetName="Field$" RowStartIndex="5">
      <LanguagetSetting Language="en" LanguageCode="" Column="Q" />
      <LanguagetSetting Language="zh-cn" LanguageCode="zh-cn" Column="S">
      </LanguagetSetting>
      <LanguagetSetting Language="zh-tw" LanguageCode="zh-tw" Column="R">
      </LanguagetSetting>
    </Setting>
  </AppSetting>-->

  <AppSetting ApplicationName="FXB" ResourcePath="..\Taifook.OMS.FXB.Common\Properties\" ResourceName="Resources.resx" IsDefault="true">
    <Setting Type="Message" SourceFilePath="..\Others\MSSF_Message.xls" IdColumn="R" DeletedColumn="H" TypeColumn="M" SheetName="Message$" RowStartIndex="5" TotalColumns="32">
      <LanguagetSetting Language="en" LanguageCode="" Column="V" />
      <LanguagetSetting Language="zh-cn" LanguageCode="zh-cn" Column="X"></LanguagetSetting>
      <LanguagetSetting Language="zh-tw" LanguageCode="zh-tw" Column="W"></LanguagetSetting>
    </Setting>
    <Setting Type="Field" SourceFilePath="..\Others\MSSF_FieldLabel.xls" IdColumn="P" DeletedColumn="D" TypeColumn="M" SheetName="Field$" RowStartIndex="5" TotalColumns="34">
      <LanguagetSetting Language="en" LanguageCode="" Column="Q" />
      <LanguagetSetting Language="zh-cn" LanguageCode="zh-cn" Column="S"></LanguagetSetting>
      <LanguagetSetting Language="zh-tw" LanguageCode="zh-tw" Column="R"></LanguagetSetting>
    </Setting>
  </AppSetting>
</AppConfigs>
